#!/bin/bash
# by fuldaros
./tools/clean.sh
rm -f gen.info
mkdir out
mkdir outkernel
mkdir outzip
export ARCH=arm64
stamp=$(date +"%H:%M:%S %Y.%m.%d");
echo "generated by fuldaros's script on "$stamp" " > gen.info
cd sources
make O=../out/paperplane porridge_pp_defconfig
cd ../
./build.sh
